#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.1
#  in conjunction with Tcl version 8.6
#    Jul 16, 2020 04:30:51 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    print('aligner_ui_support.destroy_window')
    sys.stdout.flush()

def on_about():
    print('aligner_ui_support.on_about')
    sys.stdout.flush()

def on_howto():
    print('aligner_ui_support.on_howto')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

Custom = tk.Frame  # To be updated by user with name of custom widget.

if __name__ == '__main__':
    import aligner_ui
    aligner_ui.vp_start_gui()




