
        self.Frame3 = tk.Frame(top)
        self.Frame3.place(relx=0.0, rely=0.666, relheight=0.332, relwidth=1.0)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#d9d9d9")
        self.Frame3.configure(width=125)

        self.c20 = ttk.Label(self.Frame3)
        self.c20.place(relx=0.0, rely=0.0,  relheight=1.0, relwidth=0.05)
        self.c20.configure(background="#d9d9d9")
        self.c20.configure(foreground="#000000")
        self.c20.configure(font="TkDefaultFont")
        self.c20.configure(relief="flat")
        self.c20.configure(takefocus="0")
        self.c20.configure(text='''02''')

        self.c21 = ScrolledText(self.Frame3)
        self.c21.place(relx=0.05, rely=0., relheight=1, relwidth=0.45)
        self.c21.configure(background="white")
        self.c21.configure(font=font9)
        self.c21.configure(foreground="black")
        self.c21.configure(highlightbackground="#d9d9d9")
        self.c21.configure(highlightcolor="black")
        self.c21.configure(insertbackground="black")
        self.c21.configure(insertborderwidth="3")
        self.c21.configure(selectbackground="#c4c4c4")
        self.c21.configure(selectforeground="black")
        self.c21.configure(takefocus="0")
        self.c21.configure(width=10)
        self.c21.configure(wrap="none")

        self.c22 = ScrolledText(self.Frame3)
        self.c22.place(relx=0.5, rely=0., relheight=1, relwidth=0.45)
        self.c22.configure(background="white")
        self.c22.configure(font=font9)
        self.c22.configure(foreground="black")
        self.c22.configure(highlightbackground="#d9d9d9")
        self.c22.configure(highlightcolor="black")
        self.c22.configure(insertbackground="black")
        self.c22.configure(insertborderwidth="3")
        self.c22.configure(selectbackground="#c4c4c4")
        self.c22.configure(selectforeground="black")
        self.c22.configure(takefocus="0")
        self.c22.configure(width=10)
        self.c22.configure(wrap="none")

        self.c23 = tk.Text(self.Frame3)
        self.c23.place(relx=0.95, rely=0., relheight=1, relwidth=0.05)
        self.c23.configure(background="white")
        self.c23.configure(font=font9)
        self.c23.configure(foreground="black")
        self.c23.configure(highlightbackground="#d9d9d9")
        self.c23.configure(highlightcolor="black")
        self.c23.configure(insertbackground="black")
        self.c23.configure(selectbackground="#c4c4c4")
        self.c23.configure(selectforeground="black")
        self.c23.configure(takefocus="0")
        self.c23.configure(width=10)
        self.c23.configure(wrap="word")