#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.1
#  in conjunction with Tcl version 8.6
#    Jul 18, 2020 07:55:39 PM CST  platform: Windows NT

import sys
from pathlib import Path

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import myprogressbar1_ui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Pbar (root)
    myprogressbar1_ui_support.init(root, top)
    root.mainloop()

w = None
def create_Pbar(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Pbar(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Pbar (w)
    myprogressbar1_ui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Pbar():
    global w
    w.destroy()
    w = None

class Pbar:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        self.top = top  # prepare for possible detroy
        # a widget cant destroy itself?

        iconpath = Path(__file__).parent / "align.ico"
        # top.iconbitmap("align.ico")
        top.iconbitmap(iconpath)

        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("333x34+451+184")
        top.minsize(120, 1)
        top.maxsize(1284, 781)
        top.resizable(1, 1)
        top.title("Pbar")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.TProgressbar1 = ttk.Progressbar(top)
        self.TProgressbar1.place(relx=0.0, rely=0.0, relwidth=1.0, relheight=0.0
                , height=34)
        self.TProgressbar1.configure(length="360")
        self.TProgressbar1.configure(mode="indeterminate")

        # self.TProgressbar1.start()

        # window.focus_force()
        # window.grab_set()

        # stay on the top
        top.focus_force()
        top.grab_set()

if __name__ == '__main__':
    vp_start_gui()





